#pragma once

namespace Client
{
	enum PLAYER_STATE {
		// 아이들, 대화, 걷기, 뛰기
		STATE_IDLE, STATE_IDLE_CARRY, STATE_TALK_BACK, STATE_TALK, STATE_WALK, STATE_RUN,

		// 방패만 가지고 있는 애니메이션
		STATE_SHIELD, STATE_SHIELD_F, STATE_SHIELD_B, STATE_SHIELD_L, STATE_SHIELD_R, STATE_SHIELD_HIT,

		// 칼만 가지고 있는 애니메이션
		STATE_SLASH, STATE_SLASH_LP, STATE_SLASH_F, STATE_SLASH_B, STATE_SLASH_L, STATE_SLASH_R, STATE_NORMAL_SLASH_ED, STATE_SPECIAL_SLASH_ED,

		// 칼과 방패 둘다 있는 애니메이션
		STATE_SLASH_SHIELD, STATE_SLASH_SHIELD_F, STATE_SLASH_SHIELD_B, STATE_SLASH_SHIELD_L, STATE_SLASH_SHIELD_R,

		// 벽 밀고 당기기
		STATE_PUSH, STATE_PULL,

		// 아이템 얻었을떄
		STATE_ITEM_ST, STATE_Lv25_SWRODGET_ST,

		// 점프
		STATE_JUMP,

		// 뒤로 데쉬
		STATE_DASH_CRASH,

		// 데미지 입었을때
		STATE_DMG_ELEC, STATE_DMG_QUAKE,

		// 죽음, 부활
		STATE_DEATH, STATE_RESURRECTION,

		// 좌우 버튼, 키 열기
		STATE_BUTTON_L, STATE_BUTTON_R, STATE_KEY_OPEN,

		// 필살기
		STATE_DASH_ST, STATE_DASH_LP, STATE_DASH_ED,

		// 들기
		STATE_CARRY, STATE_LAND_CARRY, STATE_JUMP_CARRY, STATE_THROW,

		STATE_END
	};

	enum POTDEMON_STATE {

		// Pot Demon
		POT_WAIT, POT_WALK, POT_STUN, POT_STUN_WAIT, POT_GETUP, POT_POP, POT_ATTACK_FIRE, POT_ATTACK_JUGGLING, POT_DEPOP, POT_POP_WAIT,

		// Demon King
		KING_POP, KING_WAIT, KING_ATTACK_JUGGLING, KING_ATTACK_FIRE, KING_DEPOP,

		// 페이즈 2 나타나기
		KING_PHASE_2_ST,

		// 페이즈 2 아이들 상태
		KING_PHASE_2_WAIT,

		// 사라지기 & 나타나기
		KING_PHASE_2_ED, KING_CLONING_APPEAR,

		// 주먹 난사 후 사라지기
		KING_CLONING_ATK_PUNCH, KING_CLONING_ATK_PUNCH_ED,

		// 원기옥을 던지기 위한 일련의 과정
		KING_CLONING_ED_WAIT, KING_CLONING_ED_THROW, KING_CLONING_ED_WAIT_2,

		// 데미지 받기, 데드
		KING_CLONING_DAMAGE, KING_CLONING_ULT_DAMAGE, KING_ATK_ULT, KING_CLONING_DEAD,

		POTDEMON_STATE_END = -1
	};

	
}

using namespace std;
using namespace Client;